@echo off
ren "public\foto strava.jpeg" "foto-strava.jpeg"
ren "public\projek ccn.jpeg" "projek-ccn.jpeg"
ren "public\logo andn.png" "logo-andn.png"
ren "public\logo ccn.jpeg" "logo-ccn.jpeg"
ren "public\logo dipodesa.jpeg" "logo-dipodesa.jpeg"
ren "public\logo himasa.jpeg" "logo-himasa.jpeg"
ren "public\logo kpm.jpeg" "logo-kpm.jpeg"
ren "public\logo kwarcab.jpeg" "logo-kwarcab.jpeg"
ren "public\logo man 4.jpeg" "logo-man-4.jpeg"
ren "public\logo mi.jpeg" "logo-mi.jpeg"
ren "public\logo unpad.jpeg" "logo-unpad.jpeg"
ren "public\sertif ccn.jpeg" "sertif-ccn.jpeg"
ren "public\sertif garuda.jpeg" "sertif-garuda.jpeg"
ren "public\sertif mc.jpeg" "sertif-mc.jpeg"
